
BAUPROJEKTE = ../Mapping

BAUPROJEKTE_BLACKLIST = "XXX_XXX_XXX"

MACROS = ./macros

FIRST_ID_CLASS_VEHICLES = 500

GLUE_ARGS1 = "tmp2/mission.sqm.skel.txt"
GLUE_ARGS2 = "configs/addOns.skel.txt" "configs/addOnsAuto.skel.txt"
GLUE_ARGS3 = "configs/classgroups.txt" "configs/classmarkers.txt"

GLUE_ARGS = $(GLUE_ARGS1) $(GLUE_ARGS2) $(GLUE_ARGS3)

GLUE = bin/glue.py

all: bauprojekte Lampen_einschalten mission.sqm mission_vanilla.sqm

clean:
	rm -rf tmp
	rm -rf tmp2

bauprojekte: clean
	cat bin/slice.sh | tr -d '\r' | tee bin/.slice_CRLF_sucks.sh; chmod 0755 bin/.slice_CRLF_sucks.sh
	mkdir -p tmp
	find $(BAUPROJEKTE) -type f -ipath '*/mission*.sqm' | sort | uniq | \
		xargs -n1 --no-run-if-empty ./bin/.slice_CRLF_sucks.sh $(BAUPROJEKTE_BLACKLIST) | \
			tee tmp/mission.autogenerated.txt

Lampen_einschalten:
	cat bin/lamps.sh | tr -d '\r' | tee bin/.lamps_CRLF_sucks.sh; chmod 0755 bin/.lamps_CRLF_sucks.sh
	mkdir -p tmp2
	./bin/.lamps_CRLF_sucks.sh tmp/mission.autogenerated.txt | tee tmp2/mission.autogenerated.txt

mission.sqm.skel.txt:
	mkdir -p tmp2
	cat configs/mission/mission.sqm.001.header.txt \
		configs/mission/mission.sqm.002.body.txt \
		configs/mission/mission.sqm.003.footer.txt | \
		tee tmp2/mission.sqm.skel.txt

#
# generates the mission with all the xCam projects (sqm files) we have
#
mission.sqm: mission.sqm.skel.txt
	@chmod 0755 $(GLUE)
	@$(GLUE) $(GLUE_ARGS) \
		"configs/classvehicles.txt tmp2/mission.autogenerated.txt" \
		"$(FIRST_ID_CLASS_VEHICLES)" "$(MACROS)" | \
	tee ../Altis/Altis_Life.Altis/$(@)

#
# generates an Altis Life mission without all our xCam projects
#
mission_vanilla.sqm: mission.sqm.skel.txt
	@chmod 0755 $(GLUE)
	@$(GLUE) $(GLUE_ARGS) \
		"configs/classvehicles.txt" \
		"$(FIRST_ID_CLASS_VEHICLES)" "$(MACROS)" | \
	tee ../Altis/Altis_Life.Altis/$(@)
